version: 2

project_name: modern-ls

before:
  hooks:
    - go mod tidy

builds:
  - id: modern-ls
    main: ./cmd/modern-ls
    binary: modern-ls
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/the-mayankjha/modern-ls/internal/cli.Version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    homepage: "https://github.com/the-mayankjha/modern-ls"
    description: "A beautiful, extremely fast, modern replacement for Unix ls."
    maintainer: "Mayank Jha"
    license: "MIT"
    formats:
      - deb
      - rpm
      - archlinux

homebrew_casks:
  - repository:
      owner: the-mayankjha
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@mayankjha.com
    homepage: "https://github.com/the-mayankjha/modern-ls"
    description: "A beautiful, extremely fast, modern replacement for Unix ls."
    license: "MIT"

scoops:
  - repository:
      owner: the-mayankjha
      name: scoop-bucket
    commit_author:
      name: goreleaserbot
      email: goreleaser@mayankjha.com
    homepage: "https://github.com/the-mayankjha/modern-ls"
    description: "A beautiful, extremely fast, modern replacement for Unix ls."
    license: "MIT"

winget:
  - name: modern-ls
    publisher: the-mayankjha
    license: MIT
    short_description: "A beautiful, extremely fast, modern replacement for Unix ls."
    repository:
      owner: the-mayankjha
      name: winget-pkgs
    commit_author:
      name: goreleaserbot
      email: goreleaser@mayankjha.com
